#!/usr/bin/env bash
# t-opencode.sh — opencode hook-tier support.
#   - `agent-fleet opencode-hooks` installs a wholly-owned plugin file under
#     ~/.config/opencode/plugins, idempotently; remove deletes it but refuses
#     to touch a file the fleet didn't generate
#   - the status hook tags the pane kind opencode and captures the session id
#   - persist-restore relaunches the pane with `opencode --session <id>`
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

echo "t-opencode:"
FAKEHOME="$(mktemp -d)"
PLUG="$FAKEHOME/cfg/opencode/plugins/agent-fleet.js"

af() { HOME="$FAKEHOME" XDG_CONFIG_HOME="$FAKEHOME/cfg" "$REPO/bin/agent-fleet" "$@"; }

check "status before install: not installed" "[[ \"\$(af opencode-hooks status)\" == 'not installed' ]]"
af opencode-hooks install >/dev/null
check "install: plugin file present" "[[ -f '$PLUG' ]]"
check "install: generation marker present" "grep -q 'generated by agent-fleet' '$PLUG'"
check "install: hook path embedded" "grep -qF '$REPO/scripts/agent-status-hook.sh' '$PLUG'"
check "install: observe-only (never sets output.status)" "! grep -q 'output.status' '$PLUG'"
check "install: all three states mapped" "grep -q '\"working\"' '$PLUG' && grep -q '\"wait\"' '$PLUG' && grep -q '\"done\"' '$PLUG'"
check "status after install: installed" "[[ \"\$(af opencode-hooks status)\" == installed* ]]"
af opencode-hooks install >/dev/null
# arithmetic compare: BSD wc pads its count with spaces, a string == fails on macOS
check "reinstall: still exactly one plugin file" "(( \$(ls '$FAKEHOME/cfg/opencode/plugins' | wc -l) == 1 ))"

# Valid JS? Best-effort syntax gate when node is around (CI runners have it).
if command -v node >/dev/null 2>&1; then
  check "plugin parses as valid JS" "node --check '$PLUG' 2>/dev/null || node --input-type=module --check < '$PLUG' 2>/dev/null"
fi

af opencode-hooks remove >/dev/null
check "remove: plugin file gone" "[[ ! -f '$PLUG' ]]"
printf '// my own plugin\n' > "$PLUG"
check "remove refuses a non-fleet file" "! af opencode-hooks remove 2>/dev/null"
check "user file survives" "[[ -f '$PLUG' ]]"

# --- hook kind-tagging + save/restore round trip -----------------------------
CACHE="$XDG_CACHE_HOME/agent-fleet"
UUID="0c0c0c0c-1d1d-2e2e-3f3f-4a4a4a4a4a4a"
mkdir -p "$WORK/x"

# A fake `opencode` keeps the respawned resume pane alive deterministically
# (same hermeticity trick as t-resume's fake claude).
FAKEBIN="$(mktemp -d)"
printf '#!/usr/bin/env bash\nsleep 300\n' > "$FAKEBIN/opencode"
chmod +x "$FAKEBIN/opencode"
export PATH="$FAKEBIN:$PATH"

boot_server __boot__ "$WORK"
tx new-session -d -s xwork -n xwork -c "$WORK/x"
sleep 0.6
wp="$(tx list-panes -t xwork -F '#{pane_id} #{?@fleet-sidenav,1,0}' | awk '$2 != "1" {print $1; exit}')"

# Simulate the plugin reporting working with the session id (JSON stdin, as
# the plugin pipes it).
printf '{"session_id":"%s"}' "$UUID" \
  | TMUX_PANE="$wp" AGENT_FLEET_NOTIFY=0 XDG_CACHE_HOME="$XDG_CACHE_HOME" \
    bash "$REPO/scripts/agent-status-hook.sh" working "$SOCK" opencode
check "hook captures opencode session id" "grep -qx '$UUID' '$CACHE/panes/$wp.session'"
check "hook tags @fleet-agent-kind opencode" "[[ \"\$(tx display-message -p -t $wp '#{@fleet-agent-kind}')\" == 'opencode' ]]"

tx kill-session -t __boot__ 2>/dev/null; sleep 0.3
"$REPO/scripts/persist-save.sh"
check "save records kind opencode" "grep -q 'opencode' '$CACHE/fleet.state'"

tx kill-server; sleep 0.4
"$REPO/scripts/persist-restore.sh"
sleep 0.6
# shellcheck disable=SC2034 # starts read inside the eval'd check() conditions below
starts="$(tx list-panes -t xwork -F '#{pane_start_command}')"
check "restore relaunches opencode --session" "grep -q 'opencode --session $UUID' <<<\"\$starts\""
check "restore does NOT use claude --resume for opencode" "! grep -q 'claude --resume $UUID' <<<\"\$starts\""

rm -rf "$FAKEHOME" "$FAKEBIN"
exit "$FAIL"
