#!/usr/bin/env bash
# theme.sh — the fleet palette. Source me; the palette is then resolved.
#
# AGENT_FLEET_THEME names a preset in conf/themes/ (default tokyo-night;
# unknown names fall back to it). Sourcing exports the nine hex slots
# (AF_THEME_*) and builds ready-made truecolor SGR escapes (T_*) for scripts
# that paint raw ANSI. Everything uses printf -v — no forks — because the
# status bar re-sources this every refresh via status.sh.
#
# The tmux side is a generated snippet: theme_write_conf renders the themed
# styles to $CACHE/theme.conf, and the base conf sources it at parse time
# through $AGENT_FLEET_THEME_CONF (exported here). The CLI and persist-restore
# call theme_write_conf before any command that could boot the server.

_af_sgr() {  # <var> <38|48> <#rrggbb> — build one SGR escape into <var>
  local h="${3#\#}"
  printf -v "$1" '\033[%s;2;%d;%d;%dm' "$2" "$((16#${h:0:2}))" "$((16#${h:2:2}))" "$((16#${h:4:2}))"
}

theme_resolve() {
  local dir="${AGENT_FLEET_ROOT:-${BASH_SOURCE[0]%/*}/..}/conf/themes"
  # Precedence: env (explicit one-shot override) > the persisted choice
  # (`agent-fleet theme <name>` writes it) > default. A FILE carries the real
  # setting because CLI calls fired by tmux keybinds run in the server's
  # environment, where a shell-profile export never arrives — env-only
  # persistence got silently reverted by the first `goto` after a switch.
  AF_THEME="${AGENT_FLEET_THEME:-}"
  if [[ -z "$AF_THEME" ]]; then
    local pf="${XDG_CONFIG_HOME:-$HOME/.config}/agent-fleet/theme"
    if [[ -r "$pf" ]]; then read -r AF_THEME < "$pf" 2>/dev/null || true; fi
  fi
  [[ -n "$AF_THEME" && -f "$dir/$AF_THEME.sh" ]] || AF_THEME="tokyo-night"
  # shellcheck source=../conf/themes/tokyo-night.sh
  source "$dir/$AF_THEME.sh"
  export AF_THEME AF_THEME_BG AF_THEME_SURFACE AF_THEME_HL AF_THEME_FG \
         AF_THEME_MUTED AF_THEME_ACCENT AF_THEME_WAIT AF_THEME_WORKING AF_THEME_DONE
  _af_sgr T_FG      38 "$AF_THEME_FG"
  _af_sgr T_MUTED   38 "$AF_THEME_MUTED"
  _af_sgr T_ACCENT  38 "$AF_THEME_ACCENT"
  _af_sgr T_WAIT    38 "$AF_THEME_WAIT"
  _af_sgr T_WORKING 38 "$AF_THEME_WORKING"
  _af_sgr T_DONE    38 "$AF_THEME_DONE"
  _af_sgr T_HL_BG   48 "$AF_THEME_HL"
}

# Render the tmux styles for the resolved palette. Atomic (tmp + mv) so a
# parsing server never sees a half-written file; failures are swallowed — a
# read-only cache just leaves the conf's static Tokyo Night in charge.
theme_write_conf() {
  local cache="${XDG_CACHE_HOME:-$HOME/.cache}/agent-fleet"
  local root="${AGENT_FLEET_ROOT:-$(cd "${BASH_SOURCE[0]%/*}/.." && pwd)}"
  local f="$cache/theme.conf" tmp="$cache/theme.conf.$$"
  mkdir -p "$cache" 2>/dev/null || true
  # shellcheck disable=SC2015 # write-then-swap idiom, not if/then/else: mv failing must still clean up the temp
  {
    printf '# generated by agent-fleet (theme: %s) — do not edit, see conf/themes/\n' "$AF_THEME"
    printf 'set -g status-style "bg=%s,fg=%s"\n' "$AF_THEME_BG" "$AF_THEME_FG"
    printf 'set -g status-left "#[bg=%s,fg=%s,bold] FLEET                        #[fg=%s,nobold]│#[default] "\n' \
      "$AF_THEME_BG" "$AF_THEME_ACCENT" "$AF_THEME_HL"
    printf 'set -g status-right "#(%s/scripts/status.sh summary)#[fg=%s] %%H:%%M "\n' "$root" "$AF_THEME_MUTED"
    printf 'setw -g window-status-current-style "bg=%s,fg=%s,bold"\n' "$AF_THEME_ACCENT" "$AF_THEME_BG"
    printf 'setw -g window-status-style "fg=%s"\n' "$AF_THEME_MUTED"
    printf 'set -g message-style "bg=%s,fg=%s"\n' "$AF_THEME_SURFACE" "$AF_THEME_FG"
    printf 'set -g mode-style "bg=%s,fg=%s"\n' "$AF_THEME_SURFACE" "$AF_THEME_FG"
    printf 'set -g pane-border-style "fg=%s"\n' "$AF_THEME_SURFACE"
    printf '%%if #{>=:#{version},3.4}\n'
    printf "set -g pane-active-border-style '#{?#{e|>:#{window_panes},2},fg=%s,fg=%s}'\n" \
      "$AF_THEME_ACCENT" "$AF_THEME_SURFACE"
    printf '%%else\n'
    printf 'set -g pane-active-border-style "fg=%s"\n' "$AF_THEME_ACCENT"
    printf '%%endif\n'
    printf 'set -g popup-border-style "fg=%s"\n' "$AF_THEME_ACCENT"
  } > "$tmp" 2>/dev/null && mv "$tmp" "$f" 2>/dev/null || rm -f "$tmp" 2>/dev/null
  return 0
}

# Shared by the rail and the picker (both source this file); fork-free so the
# rail's render loop can call it per row.
# shellcheck disable=SC2034 # AGE is the out-param, read by the sourcing renderers
fmt_age() {  # <seconds> -> AGE ("45s"/"4m"/"2h")
  local s="$1"
  if   (( s < 60 ));   then AGE="${s}s"
  elif (( s < 3600 )); then AGE="$(( s / 60 ))m"
  else                      AGE="$(( s / 3600 ))h"
  fi
}

export AGENT_FLEET_THEME_CONF="${XDG_CACHE_HOME:-$HOME/.cache}/agent-fleet/theme.conf"
theme_resolve
